# Generated by Django 4.1 on 2023-08-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebaseauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nacimiento',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='foto',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fecha_ingreso',
            new_name='registerDate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='sexo',
            new_name='sex',
        ),
    ]
