# Generated by Django 4.2.4 on 2023-11-18 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('idCity', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('idDictionary', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.IntegerField()),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('idImage', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('idImageType', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('visible', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('idProject', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapas.city')),
                ('users', models.ManyToManyField(related_name='user_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('derived', models.BooleanField(default=False)),
                ('idImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapas.image')),
                ('idProject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapas.project')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='idImageType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapas.imagetype'),
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('idCoordinate', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', models.JSONField()),
                ('properties', models.JSONField()),
                ('type', models.CharField(max_length=100)),
                ('idImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapas.image')),
            ],
        ),
    ]
